### ISSUE TITLE
tablenos writing to stderr with header-includes reminder

### ISSUE THREAD

**Issue by danielhep** [tomduck/pandoc-tablenos#16]
I'm getting the following error on the output when I run pandoc with tablenos added as a filter. Pandoc runs successfully and the table even generates fine. The header includes are showing up in the generated LaTeX file as well.

```Wrote the following blocks to header-includes. If you use pandoc's --include-in-header option then you will need to manually include these yourself.```

**Comment by tomduck** [comment]
Hi there.  Sorry for the long wait.  What you observed was just a warning.  You can control what kinds of warnings are given.  As per the README:

> Warning messages are a new feature of pandoc-tablenos. The meta variable tablenos-warning-level may be set to `0`, `1`, or `2` depending on the degree of warnings desired. Warning level `1` will alert users to bad references, malformed attributes, and unknown meta variables. Warning level `2` (the default) adds informational messages that should be helpful with debugging. Level `0` turns all messages off.

The default was set to 2 because how/what blocks are injected was changed pretty substantially with the 2.0 release.

I think that this probably resolved the Issue, and so will close it.  Please re-open it if there are further concerns.

**Comment by Benjamin-Lee** [comment]
For reference for future users, I got this warning when I added a table without a caption. Adding the caption and tag made the warning go away.
